version: '3.1'

services:
  geniesys:
    image: irusri/docker4geniesys:latest
    ports:
      - "80:80"
      - "3002:3006"
    environment:
      - "MYSQL_ADMIN_PASS=mypass"
    volumes: 
      - "geniesys:/app/geniesys"
      - "mysql:/var/lib/mysql"
volumes:
  geniesys:
  mysql:
